typo fix and deprecation warning for MatrouskaEncoder
koaning/embetter pull request #100
Opened 2024-04-10 17:44 UTC by anopsy

I added deprecation warning using warn, because I noticed this solution in sklego (KlusterFoldValidation). If you prefer me to use deprecated-decorator, just let me know. Not sure if I changed __init__ correctly but they made importing MatryoshkaEncoder possible.

2024-04-10 19:23 UTC, koaning requested changes
Thanks. 

Could you also make sure the docs/readme markdown doc are updated?

2024-04-11 06:00 UTC, anopsy commented
<facepalm> Sorry, I'm on it, I will also adjust [tests/test_text.py](https://github.com/koaning/embetter/blob/dae4c0207edde0036d4c3a3c7a46cb22d5883e65/tests/test_text.py#L16)

2024-04-11 12:11 UTC, anopsy commented
Let me know if I correctly assumed that the README.md, text.md and tests don't need mentions of both Matrouska and Matryoshka.

2024-04-11 18:50 UTC, koaning approved these changes
LGTM. Thanks :)

2024-04-11 18:50 UTC, merged